sudo: false
dist: xenial

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy

matrix:
  fast_finish: true
  allow_failures:
    - python: pypy

  include:
    - os: osx
      language: generic
      env: TOXENV=py37

    - python: 3.7
      env: TOXENV="isort,lint,coverage"
      script: tox
      after_success:
        - pip install codecov && codecov
        - coverage report

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew upgrade python;
      python3 -m venv venv;
      source venv/bin/activate;
    fi
install:
  - pip install -U six setuptools wheel
  - pip install -U tox tox-travis
  - python setup.py bdist_wheel
script: tox --installpkg ./dist/tox_venv-*.whl
